name: pdfviewer
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  dio: ^4.0.4
  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation
  # and to access the concrete implementation from everywhere in your App
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.13
  splashscreen: ^1.3.5
  advance_pdf_viewer: ^2.0.1
  rflutter_alert: ^2.0.4
  dropdownfield: ^1.0.3
  cupertino_date_textbox: ^1.0.1
  path_provider: ^2.0.9
  flutter_speed_dial: ^5.0.0+1
  pagination_view:
    git:
      url: https://github.com/excogitatr/pagination_view.git
      ref: master
  flutter_pdfview:
    git:
      url: https://github.com/endigo/flutter_pdfview.git
      ref: master
  multiselect_formfield: ^0.1.7
  file_picker: ^4.4.0
  flutter_windowmanager: ^0.2.0
  local_auth: ^1.1.11
  smart_select: ^4.3.2
  clipboard: ^0.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/user.png
    - assets/images/search.png
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
    - family: Arslan
      fonts:
        - asset: assets/fonts/arslan.ttf
    - family: Jazeera
      fonts:
        - asset: assets/fonts/Jazeera.ttf
    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar.ttf